package config

import (
	"os"
)

var (
	GLOBAL_SCRAPE_INTERVAL     = os.Getenv("GLOBAL_SCRAPE_INTERVAL")
	GLOBAL_EVALUATION_INTERVAL = os.Getenv("GLOBAL_EVALUATION_INTERVAL")
	GLOBAL_SCRAPE_TIMEOUT      = os.Getenv("GLOBAL_SCRAPE_TIMEOUT")
)
